### ISSUE TITLE
Document differences between Node.js version and browser version

### ISSUE THREAD

**Issue by alexkreidler** [rubensworks/rdf-dereference.js#21]
[Here's](https://privatebin.net/?3dd9267a5d19a633#ZASC5WpCsWUPJ2NK5tvakZ2Jmnetz5zbqtGhTbg4P9k) the result of `rdf-dereference http://schema.org/Person`.

Then I do the same thing in the browser and get [this](https://privatebin.net/?069edebe90c0c012#9L1yUBGVzsfQSRrCFjGm2m1aFUBEWvwGBoxbcC2ZzPZJ), which is significantly less and missing many of the triples I need.

I'm wondering if the downstream communica packages have different behaviors in Node than the browser, because I looked at the difference between `RdfDereferencer-browser.ts` and `RdfDereferencer.ts `, and there's not much. It would be great to put that in documentation somewhere.

Thanks!

**Comment by rubensworks** [comment]
The lower number of triples in the browser may be because of CORS issues with schema.org. (you can confirm this by attaching an error-listener to the stream)

I ran into this a number of times myself, and is caused by a recent change in schema.org: https://github.com/schemaorg/schemaorg/issues/2578#issuecomment-652349679

In any case, there should not be any difference in behaviour between Node and browsers.

**Comment by alexkreidler** [comment]
Yes, this was an issue with CORS and not related to this library or Comunica
